### model
model_name_or_path: /root/a100_nas_lvbo/peixunban/002754_lvbo/SFT/hf_pt/olmo1b_hf_pt_2024_12_14_15_33_51
run_name: sft_olmo1b_phy_math

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: physics, physics-arxiv # tulu3-A, tulu3-B # physics, physics-arxiv, tulu-3-math, tulu-3-math-grade # physics-tulu3-A, # mllm_demo,identity
template: alpaca
cutoff_len: 2048
max_samples: 50000000
overwrite_cache: true
preprocessing_num_workers: 20

### output
output_dir: /root/a100_nas_lvbo/peixunban/002754_lvbo/SFT/hf_pt/olmo1b_hf_pt_2024_12_14_test
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8 # 16 # 12
gradient_accumulation_steps: 2 # 2
learning_rate: 1.0e-5 # 5.0e-5 # 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 12
eval_strategy: steps
eval_steps: 1000
