### model
model_name_or_path: /root/a100_nas_lvbo/peixunban/002754_lvbo/SFT/hf_pt/olmo1b_2024_12_09_01_44_49
run_name: sft_olmo1b

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: physics-tulu3-A # mllm_demo,identity
template: alpaca
cutoff_len: 2048
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/a100_nas_lvbo/peixunban/002754_lvbo/SFT/sft_pt/olmo1b_2024_12_09_01_44_49
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
